name: amzx
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  country_icons: ^2.0.2
  syncfusion_flutter_charts: ^20.1.57
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.2
  introduction_screen: ^3.0.2
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  hive: ^2.2.1
  dio: ^4.0.6
  build_runner: ^2.1.11
  hive_flutter: ^1.1.0
  another_flushbar: ^1.10.29
  flutter_inappwebview: ^5.4.3+7
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/