name: amzx
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-80.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: ^20.1.52
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.0
  introduction_screen: ^3.0.1
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  provider: ^6.0.2
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0
  get_it: ^7.2.0
  hive: ^2.1.0
  dio: ^4.0.6
  build_runner: ^2.1.10
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/